version: "3.9"

services:
  # Backend (Django + Gunicorn)
  api:
    image: 401876438340.dkr.ecr.eu-west-1.amazonaws.com/peyjabanki-api:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - ALLOWED_HOSTS=*
    volumes:
      - static_volume:/app/static
    depends_on:
      - db

  # Frontend + Nginx
  frontend:
    image: 401876438340.dkr.ecr.eu-west-1.amazonaws.com/peyjabanki-frontend:latest
    ports:
      - "80:80"    # Only needed for redirect to HTTPS
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - api

  # Database
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static_volume:
